export const communityArchiveTeams = [
  { name: "第一届队伍1", players: ["隔壁老王", "叉烧包", "害怕否决", "友善的火元素", "善良的小姨子"], championshipCount: 0 },
  { name: "第一届队伍2", players: ["The Bad Guy", "chairchen", "饭饭", "JackBot", "iScream"], championshipCount: 1 },
  { name: "第二届队伍1", players: ["友善的火元素", "大鹅", "王绿茶", "超凶残的猫", "suzuki"], championshipCount: 0 },
  { name: "第二届队伍2", players: ["派", "up ships！！", "杀猪酱", "无敌LOL大王", "iScream"], championshipCount: 1 },
  { name: "食神", players: ["iScream", "饭饭", "王绿茶", "隔壁老王", "友善的火元素", "红色巧克李"], championshipCount: 0 },
  { name: "牛牛小小说话吊吊1.0", players: ["鲨鱼辣椒", "geihei", "杀猪酱", "up ships！！", "无敌LOL大王", "黄师傅龙虾", "叉烧包"], championshipCount: 1 },
  { name: "草帽小子海贼团1.0", players: ["黄师傅龙虾", "最近不太行", "友善的火元素", "饭饭", "烟雨", "邓布利多"], championshipCount: 1 },
  { name: "牛牛小小说话吊吊2.0", players: ["杀猪酱", "V", "无敌LOL大王", "叉烧包", "geihei", "up ships！！"], championshipCount: 0 },
  { name: "花开富贵", players: ["大威天龙", "冷暴力大法师", "听风", "鹅城九筒", "M", "geihei", "大鹅"], championshipCount: 3 },
  { name: "草帽小子海贼团2.0", players: ["友善的火元素", "派", "烟雨", "邓布利多", "饭饭", "茶"], championshipCount: 0 },
  { name: "草帽小子海贼团3.0", players: ["通天兔", "potong雪糕大王", "stupid", "黄师傅龙虾", "最近不太行", "杀猪酱"], championshipCount: 0 },
  { name: "雪王", players: ["potong雪糕大王", "stupid", "七", "蛋炒饭", "冬木之虎", "王绿茶"], championshipCount: 0 },
  { name: "what's up", players: ["鹅城九筒", "The Bad Guy", "XXBee", "七", "喜剧演员", "海鸥不再眷恋大海"], championshipCount: 0 },
  { name: "患者", players: ["cook", "玉玉症患者", "德普大王", "伍六七", "+ +", "小王子"], championshipCount: 3 },
  { name: "西浦军校教导队", players: ["杀猪酱", "up ships！！", "入江", "V", "无敌LOL大王"], championshipCount: 0 },
  { name: "花开富贵2.0", players: ["geihei", "大威天龙", "冷暴力大法师", "听风", "M", "赢一把睡觉"], championshipCount: 0 },
  { name: "医生", players: ["赢一把睡觉", "potong雪糕大王", "八", "叫我女王大人！", "一瓶橙"], championshipCount: 0 }
] as const;

export const communityArchivePlayers = [
  { name: "隔壁老王", currentTeamName: null, formerTeamNames: ["食神", "第一届队伍1"], championshipCount: 0 },
  { name: "叉烧包", currentTeamName: null, formerTeamNames: ["第一届队伍1", "牛牛小小说话吊吊1.0", "牛牛小小说话吊吊2.0"], championshipCount: 1 },
  { name: "害怕否决", currentTeamName: null, formerTeamNames: ["第一届队伍1"], championshipCount: 0 },
  { name: "友善的火元素", currentTeamName: null, formerTeamNames: ["食神", "第一届队伍1", "第二届队伍1", "草帽小子海贼团1.0", "草帽小子海贼团2.0"], championshipCount: 1 },
  { name: "善良的小姨子", currentTeamName: null, formerTeamNames: ["第一届队伍1"], championshipCount: 0 },
  { name: "The Bad Guy", currentTeamName: null, formerTeamNames: ["第一届队伍2", "what's up"], championshipCount: 1 },
  { name: "chairchen", currentTeamName: null, formerTeamNames: ["第一届队伍2"], championshipCount: 1 },
  { name: "饭饭", currentTeamName: null, formerTeamNames: ["食神", "第一届队伍2", "草帽小子海贼团1.0", "草帽小子海贼团2.0"], championshipCount: 2 },
  { name: "JackBot", currentTeamName: null, formerTeamNames: ["第一届队伍2"], championshipCount: 1 },
  { name: "iScream", currentTeamName: null, formerTeamNames: ["第二届队伍2", "食神", "第一届队伍2"], championshipCount: 2 },
  { name: "大鹅", currentTeamName: null, formerTeamNames: ["第二届队伍1", "花开富贵"], championshipCount: 3 },
  { name: "王绿茶", currentTeamName: null, formerTeamNames: ["食神", "第二届队伍1", "雪王"], championshipCount: 0 },
  { name: "超凶残的猫", currentTeamName: null, formerTeamNames: ["第二届队伍1"], championshipCount: 0 },
  { name: "suzuki", currentTeamName: null, formerTeamNames: ["第二届队伍1"], championshipCount: 0 },
  { name: "派", currentTeamName: null, formerTeamNames: ["第二届队伍2", "草帽小子海贼团2.0"], championshipCount: 1 },
  { name: "up ships！！", currentTeamName: null, formerTeamNames: ["第二届队伍2", "牛牛小小说话吊吊1.0", "牛牛小小说话吊吊2.0", "西浦军校教导队"], championshipCount: 2 },
  { name: "杀猪酱", currentTeamName: null, formerTeamNames: ["第二届队伍2", "牛牛小小说话吊吊1.0", "牛牛小小说话吊吊2.0", "草帽小子海贼团3.0", "西浦军校教导队"], championshipCount: 2 },
  { name: "无敌LOL大王", currentTeamName: null, formerTeamNames: ["第二届队伍2", "牛牛小小说话吊吊1.0", "牛牛小小说话吊吊2.0", "西浦军校教导队"], championshipCount: 2 },
  { name: "红色巧克李", currentTeamName: null, formerTeamNames: ["食神"], championshipCount: 0 },
  { name: "鲨鱼辣椒", currentTeamName: null, formerTeamNames: ["牛牛小小说话吊吊1.0"], championshipCount: 1 },
  { name: "geihei", currentTeamName: null, formerTeamNames: ["牛牛小小说话吊吊1.0", "牛牛小小说话吊吊2.0", "花开富贵", "花开富贵2.0"], championshipCount: 4 },
  { name: "黄师傅龙虾", currentTeamName: null, formerTeamNames: ["牛牛小小说话吊吊1.0", "草帽小子海贼团1.0", "草帽小子海贼团3.0"], championshipCount: 2 },
  { name: "最近不太行", currentTeamName: null, formerTeamNames: ["草帽小子海贼团1.0", "草帽小子海贼团3.0"], championshipCount: 1 },
  { name: "烟雨", currentTeamName: null, formerTeamNames: ["草帽小子海贼团1.0", "草帽小子海贼团2.0"], championshipCount: 1 },
  { name: "邓布利多", currentTeamName: null, formerTeamNames: ["草帽小子海贼团1.0", "草帽小子海贼团2.0"], championshipCount: 1 },
  { name: "V", currentTeamName: null, formerTeamNames: ["牛牛小小说话吊吊2.0", "西浦军校教导队"], championshipCount: 0 },
  { name: "大威天龙", currentTeamName: null, formerTeamNames: ["花开富贵", "花开富贵2.0"], championshipCount: 3 },
  { name: "冷暴力大法师", currentTeamName: null, formerTeamNames: ["花开富贵", "花开富贵2.0"], championshipCount: 3 },
  { name: "听风", currentTeamName: null, formerTeamNames: ["花开富贵", "花开富贵2.0"], championshipCount: 3 },
  { name: "鹅城九筒", currentTeamName: null, formerTeamNames: ["花开富贵", "what's up"], championshipCount: 3 },
  { name: "M", currentTeamName: null, formerTeamNames: ["花开富贵", "花开富贵2.0"], championshipCount: 3 },
  { name: "茶", currentTeamName: null, formerTeamNames: ["草帽小子海贼团2.0"], championshipCount: 0 },
  { name: "stupid", currentTeamName: null, formerTeamNames: ["雪王", "草帽小子海贼团3.0"], championshipCount: 0 },
  { name: "potong雪糕大王", currentTeamName: null, formerTeamNames: ["雪王", "草帽小子海贼团3.0", "医生"], championshipCount: 0 },
  { name: "通天兔", currentTeamName: null, formerTeamNames: ["草帽小子海贼团3.0"], championshipCount: 0 },
  { name: "七", currentTeamName: null, formerTeamNames: ["雪王", "what's up"], championshipCount: 0 },
  { name: "蛋炒饭", currentTeamName: null, formerTeamNames: ["雪王"], championshipCount: 0 },
  { name: "冬木之虎", currentTeamName: null, formerTeamNames: ["雪王"], championshipCount: 0 },
  { name: "XXBee", currentTeamName: null, formerTeamNames: ["what's up"], championshipCount: 0 },
  { name: "喜剧演员", currentTeamName: null, formerTeamNames: ["what's up"], championshipCount: 0 },
  { name: "海鸥不再眷恋大海", currentTeamName: null, formerTeamNames: ["what's up"], championshipCount: 0 },
  { name: "cook", currentTeamName: null, formerTeamNames: ["患者"], championshipCount: 3 },
  { name: "德普大王", currentTeamName: null, formerTeamNames: ["患者"], championshipCount: 3 },
  { name: "玉玉症患者", currentTeamName: null, formerTeamNames: ["患者"], championshipCount: 3 },
  { name: "伍六七", currentTeamName: null, formerTeamNames: ["患者"], championshipCount: 3 },
  { name: "+ +", currentTeamName: null, formerTeamNames: ["患者"], championshipCount: 3 },
  { name: "入江", currentTeamName: null, formerTeamNames: ["西浦军校教导队"], championshipCount: 0 },
  { name: "赢一把睡觉", currentTeamName: null, formerTeamNames: ["花开富贵2.0", "医生"], championshipCount: 0 },
  { name: "小王子", currentTeamName: null, formerTeamNames: ["患者"], championshipCount: 3 },
  { name: "八", currentTeamName: null, formerTeamNames: ["医生"], championshipCount: 0 },
  { name: "叫我女王大人！", currentTeamName: null, formerTeamNames: ["医生"], championshipCount: 0 },
  { name: "一瓶橙", currentTeamName: null, formerTeamNames: ["医生"], championshipCount: 0 }
] as const;

export const communityArchiveCups = [
  { title: "第一届先锋杯", scheduledAt: "2025-11-23T00:00:00.000Z", participantTeamNames: ["第一届队伍1", "第一届队伍2"], championTeamName: "第一届队伍2" },
  { title: "第二届先锋杯", scheduledAt: "2025-11-28T00:00:00.000Z", participantTeamNames: ["第二届队伍1", "第二届队伍2"], championTeamName: "第二届队伍2" },
  { title: "第三届先锋杯", scheduledAt: "2025-12-05T00:00:00.000Z", participantTeamNames: ["食神", "牛牛小小说话吊吊1.0"], championTeamName: "牛牛小小说话吊吊1.0" },
  { title: "第四届先锋杯", scheduledAt: "2025-12-12T00:00:00.000Z", participantTeamNames: ["草帽小子海贼团1.0", "牛牛小小说话吊吊2.0"], championTeamName: "草帽小子海贼团1.0" },
  { title: "第五届先锋杯", scheduledAt: "2025-12-19T00:00:00.000Z", participantTeamNames: ["花开富贵", "草帽小子海贼团2.0"], championTeamName: "花开富贵" },
  { title: "第六届先锋杯", scheduledAt: "2025-12-26T00:00:00.000Z", participantTeamNames: ["花开富贵", "草帽小子海贼团3.0"], championTeamName: "花开富贵" },
  { title: "第七届先锋杯", scheduledAt: "2026-01-09T00:00:00.000Z", participantTeamNames: ["花开富贵", "雪王"], championTeamName: "花开富贵" },
  { title: "第八届先锋杯", scheduledAt: "2026-01-23T00:00:00.000Z", participantTeamNames: ["what's up", "患者", "西浦军校教导队", "花开富贵2.0"], championTeamName: "患者" },
  { title: "第九届先锋杯", scheduledAt: "2026-01-30T00:00:00.000Z", participantTeamNames: ["花开富贵", "患者"], championTeamName: "患者" },
  { title: "第十届先锋杯", scheduledAt: "2026-02-06T00:00:00.000Z", participantTeamNames: ["医生", "患者"], championTeamName: "患者" }
] as const;